<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Communication.Network.TCP.Server</PackageId>
    <Version>1.0.1</Version>
    <Authors>BIGSUNGG</Authors>
    <Description>TCP 소켓 기반 서버 라이브러리 (.NET Standard 2.1, Unity 호환).</Description>
    <RepositoryUrl>https://github.com/BIGSUNGG/DS_Communication.git</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

</Project>
