<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\Communication.Shared\Communication.Shared.csproj" />
    <ProjectReference Include="..\..\Source\Communication.Network.TCP.Shared\Communication.Network.TCP.Shared.csproj" />
    <ProjectReference Include="..\..\Source\Communication.Network.TCP.Server\Communication.Network.TCP.Server.csproj" />
    <ProjectReference Include="..\..\Source\Communication.Network.TCP.Client\Communication.Network.TCP.Client.csproj" />
    <ProjectReference Include="..\..\Source\Communication.Network.RUDP.Shared\Communication.Network.RUDP.Shared.csproj" />
    <ProjectReference Include="..\..\Source\Communication.Network.RUDP.Server\Communication.Network.RUDP.Server.csproj" />
    <ProjectReference Include="..\..\Source\Communication.Network.RUDP.Client\Communication.Network.RUDP.Client.csproj" />
  </ItemGroup>

</Project>
